/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "on-surface": "#101c2a",
        "primary-container": "#ff6b35",
        "on-tertiary-fixed": "#001c39",
        error: "#ba1a1a",
        "outline-variant": "#e1bfb5",
        "secondary-fixed-dim": "#53de9e",
        outline: "#8d7168",
        "tertiary-container": "#469cfc",
        "on-primary-fixed-variant": "#832600",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#390c00",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#a4c9ff",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        surface: "#f8f9ff",
        "on-primary-container": "#5f1900",
        "on-secondary-container": "#007149",
        "on-tertiary-fixed-variant": "#004883",
        "surface-tint": "#ab3500",
        tertiary: "#0060ac",
        "surface-container-high": "#dde9fc",
        "error-container": "#ffdad6",
        "on-background": "#101c2a",
        "surface-variant": "#d7e3f6",
        "on-tertiary-container": "#00325f",
        "secondary-container": "#6ff8b5",
        "inverse-primary": "#ffb59d",
        "surface-container": "#e4efff",
        "surface-container-low": "#eef4ff",
        primary: "#ab3500",
        "surface-container-highest": "#d7e3f6",
        "on-secondary": "#ffffff",
        background: "#f8f9ff",
        "surface-dim": "#cfdbee",
        "secondary-fixed": "#73fbb8",
        "on-surface-variant": "#594139",
        "primary-fixed-dim": "#ffb59d",
        secondary: "#006c46",
        "inverse-surface": "#26313f",
        "on-error": "#ffffff",
        "primary-fixed": "#ffdbd0",
        "on-secondary-fixed-variant": "#005233",
        "inverse-on-surface": "#e9f1ff",
        "on-secondary-fixed": "#002112",
        "tertiary-fixed": "#d4e3ff",
        crema: "#F8F5F1",
        "deep-blue": "#0A3D62",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "auto",
        "margin-mobile": "16px",
        gutter: "24px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        "max-width": "1200px",
        xs: "4px",
        base: "8px",
        sm: "12px",
      },
      fontFamily: {
        "headline-md": ["Manrope"],
        "label-md": ["Plus Jakarta Sans"],
        caption: ["Plus Jakarta Sans"],
        "headline-lg": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-xl": ["Manrope"],
        "body-lg": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "headline-lg-mobile": [
          "28px",
          { lineHeight: "36px", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
